development:
  secret_key_base: 29056d2025a35ffa5d5a9733e44656c8ff584d8f92bf88b340de7fbca3f0af30de5d53b45594f967205d9a7ab0ee35c08adcfd893460fbb6ab685ce6b2f7ff05$
  base_url: https://walletbuddy.poshvine.com
  REDIS:
    server: 127.0.0.1
    port: 6379
  use_s3_for_storage: true
  maps_api_key: AIzaSyAzzgR33zb3Fv_GuCd3ix9WFRKI2Pnv75c
  AUTH0:
    client_id: 6f35aaX1F2620eqicMTJJa4neUqcOHVP
    client_secret: lzGnInW2aHmcXYlQoP5qU8ygS8N-ilwPqk6bEMo8s3zyiSwLPvghcsBuR2uYrogg
    domain: sso-dev.jetprivilege.com
    callback_url: http://jetprivilege.poshvine.com/auth/auth0/callback
    sso_url: https://sso-dev.jetprivilege.com
  CASHFREE:
    payment_client_id: 29888ec826fe2e179578ca508892
    payment_client_key: a8722bfb32d4cb6c0995b3853a096db4f37b6727
    payment_client_salt: eCwWELxi
    url: https://test.cashfree.com
    api_url: https://test.cashfree.com
    payout_id: CF2988FKC2MKJ7E466IMM
    payout_secret: f90d739de7ee375e6b2bca21fcabdc770472991c
    payout_url: https://payout-gamma.cashfree.com/payout/v1
  AWS:
    s3_bucket: walletbuddy-staging
    s3_region: ap-southeast-1
    access_key_id: AKIAIEGZVKRCPSRYOZVQ
    secret_access_key: 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
  SIMPL:
    client_secret: eaed71a9e90c991c2a6ec5ea6e65022d
    approval_url: https://sandbox-approvals-api.getsimpl.com/api/v2/simpl_buy/server/approved
    transaction_url: https://sandbox-api.getsimpl.com/api/v1.1/transactions
  JET:
    voucher_verification_url: https://jppluat.vernost.in/jppluat/promocodes/voucherverification
    voucher_verification_key: 6HG24SjFoE5lEA2xulm3r8berVSJi2wk6LB0uwjY
  current_property_hotel_url: https://externalapi.poshvine.com/
  CONTENTFUL:
    access_token: 7ac531648a1b5e1dab6c18b0979f822a5aad0fe5f1109829b8a197eb2be4b84c
    base_url: https://cdn.contentful.com
    space_id: kk2bw5ojx476
    environment: master
